name: Daily LeetCode WhatsApp Notification

on:
  schedule:
    - cron: "0 4 * * *"  # Every day at 9:30 AM IST
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          ACCOUNT_SID: ${{ secrets.TWILIO_SID }}
          AUTH_TOKEN: ${{ secrets.TWILIO_AUTH }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
        run: python main.py
